### ISSUE TITLE
`semantic-release`

### ISSUE THREAD

**Issue by AbhiPrasad** [43081j/ecosystem-cleanup#58] opened 2024-06-29 16:25 UTC
tracked upstream here: https://github.com/semantic-release/semantic-release/issues/3372

[semantic-release](https://npmgraph.js.org/?q=semantic-release) has quite the dependency graph, loading 110 MB / 493 dependencies. It would be nice if we could reduce the number of dependencies here.

[1.2 mil weekly downloads](https://www.npmjs.com/package/semantic-release/), so a great opportunity to improve the ecosystem here.

**Comment by AbhiPrasad** [comment] 2024-06-29 16:42
oops I found https://github.com/43081j/ecosystem-cleanup/issues/20 right after - sorry for the duplicate! I can close this need be.

**Comment by 43081j** [comment] 2024-06-29 22:46
closing as duplicate of #20 

@AbhiPrasad please do update #20 with your issue though!

**Closed by 43081j** 2024-06-29 22:46 UTC
